export interface ThemeOption {
  id: string
  label: string
  icon: string
  description: string
}

export const themes: ThemeOption[] = [
  {
    id: 'reflection',
    label: 'Inner Reflection',
    icon: '☽',
    description: 'Go inward. Explore your thoughts, feelings, and patterns.',
  },
  {
    id: 'manifestation',
    label: 'Manifestation',
    icon: '✦',
    description: 'Visualise your future. Set intentions. Call it in.',
  },
  {
    id: 'health',
    label: 'Health & Wellbeing',
    icon: '◎',
    description: 'Check in with your body, mind, and rest.',
  },
  {
    id: 'relationships',
    label: 'Relationships',
    icon: '❧',
    description: 'The people in your life and how you connect.',
  },
  {
    id: 'gratitude',
    label: 'Gratitude & Joy',
    icon: '❋',
    description: 'Notice the good. The small things. The big ones too.',
  },
  {
    id: 'growth',
    label: 'Personal Growth',
    icon: '↑',
    description: 'Challenge yourself. Grow. Become who you want to be.',
  },
]

const themedPrompts: Record<string, string[]> = {
  reflection: [
    "What is one thing you've been avoiding thinking about?",
    "How is your personality different in front of family, friends, and strangers?",
    "What do you think about as you are falling asleep?",
    "What makes you feel like a child again?",
    "What is troubling you the most at this moment?",
    "What has been on your mind lately?",
    "When do you feel proud?",
    "What is something you haven't been honest with yourself about?",
    "What is the dominant emotion in your life right now?",
    "Do you feel mentally like your age?",
    "What do you wish people understood about you?",
    "What has been your biggest personal transformation?",
    "What makes you laugh uncontrollably?",
    "How do you define happiness?",
    "What is something you wish you had done sooner?",
    "What do you find beautiful about the world?",
    "How do you handle criticism?",
    "What is your biggest fear, and how do you deal with it?",
    "What is the last dream you remember?",
    "How do you express your emotions?",
    "What is something you've been struggling to let go of?",
    "How do you feel about solitude?",
    "What does your ideal day look like?",
    "What season of your life are you in right now?",
    "Write about a belief you hold that you've never questioned.",
    "What are you pretending not to know?",
    "What story about yourself are you ready to let go of?",
    "What are you in the middle of figuring out?",
    "Describe the version of yourself you're most proud of.",
    "How does writing help you process emotions?",
    "Write a letter to the person you were five years ago.",
  ],
  manifestation: [
    "What is something free that you're grateful for?",
    "When do you feel proud of yourself?",
    "What are three things you feel lucky to have?",
    "What are you looking forward to tomorrow?",
    "What is your favourite memory from the past month?",
    "What is one thing you're proud of overcoming?",
    "What does your soul crave?",
    "What limiting beliefs are holding you back?",
    "What would you do if you knew you would succeed?",
    "What do you need to let go of?",
    "What is holding you back from going after your dream life?",
    "What are 3 intentions you can set to help you manifest your dream life?",
    "How can you show up more for yourself every day?",
    "Describe your dream life as if you already are living it.",
    "What does your ideal daily routine look like?",
    "Write out what your dream job looks like and feels like.",
    "Write out 10 quality traits that you love about yourself.",
    "What does success mean to you?",
    "What fears are you ready to let go of?",
    "When do you feel the happiest?",
    "What do you need to release to be the happiest version of you?",
    "Describe yourself as if you were describing someone you love wholeheartedly.",
    "What are you most proud of yourself for?",
    "Your goal for the next 30 days.",
    "Where are you 5 years from now?",
    "What advice does future you have?",
    "Pick 3 power words to live by.",
    "How can you cultivate more joy in life?",
    "What do you want to attract more of in life?",
    "Write a thank-you letter to yourself.",
    "What aligned actions can you take to close the gap between now and your dream life?",
  ],
  health: [
    "How are you actually feeling right now — physically and emotionally?",
    "Write about what rest means to you.",
    "When did you last truly recharge? What did that look like?",
    "What does your body need that you've been ignoring?",
    "What does slowing down feel like for you?",
    "Describe your relationship with sleep.",
    "What does your body do well that you rarely acknowledge?",
    "Write about the last time you felt strong.",
    "What self-care actually works for you, beyond the obvious?",
    "How do you deal with bad body image days?",
    "What is an emotion you find the most challenging to manage?",
    "How do you recharge after a busy day?",
    "What is something you're avoiding doing for your health?",
    "What is your favourite way to stay active?",
    "How do you manage stress in daily life?",
    "What is one healthy habit you'd like to develop?",
    "How do you prioritize mental health in your routine?",
    "What is a self-care activity that always helps you relax?",
    "How do you practice mindfulness?",
    "What is one way you can improve your sleep habits?",
    "What are 3 ways to take better care of your health?",
    "How do you handle feelings of burnout?",
    "What is a way you connect with nature to improve your health?",
    "What is a small change you can make to improve your wellbeing?",
    "How do you create a calm and peaceful environment at home?",
    "What is your favourite way to unwind at the end of the day?",
    "Describe a typical 24 hours for you.",
    "How do you show kindness to yourself?",
    "What is one habit you'd like to stop for better health?",
    "How do you stay grounded during chaotic times?",
    "How are you doing, really?",
  ],
  relationships: [
    "Write about someone you miss.",
    "Describe a conversation that changed how you see things.",
    "Who in your life deserves more appreciation?",
    "Write about a friendship that has shaped you.",
    "What do you wish people understood about you?",
    "Describe a moment when a stranger was unexpectedly kind.",
    "What do you bring to the people around you?",
    "Who do you feel most yourself around?",
    "Write about a moment of unexpected connection.",
    "Who is your biggest cheerleader?",
    "How can you be a better friend?",
    "Who makes you instantly happy?",
    "What is a quality you value most in your friends?",
    "How do you set boundaries in relationships?",
    "What is one thing you'd like to improve in your relationships?",
    "What is a fond memory with a close friend or family member?",
    "What is your favourite way to spend time with loved ones?",
    "What is one lesson a past relationship has taught you?",
    "How do you maintain long-distance friendships?",
    "What is a special tradition you share with friends or family?",
    "Recount the last conversation you had with a stranger.",
    "Write about a funny story passed down in your family.",
    "What is a quality you admire in others?",
    "Write about a memory that involves a handwritten letter.",
    "What advice would you give yourself a year ago?",
    "How do you make people feel appreciated?",
    "What is something you admire in your parents or guardians?",
    "What does love mean to me?",
    "Valentine's Day — love it or loathe it?",
    "How do you recover from social burnout?",
    "What is your ultimate goal in your social life?",
  ],
  gratitude: [
    "Describe a small moment from this week that deserves more attention.",
    "What ordinary thing in your life would you miss most?",
    "Write about someone who has shaped who you are without knowing it.",
    "What does home mean to you right now?",
    "Describe the last time you were completely present in a moment.",
    "What sounds, smells, or textures instantly make you feel safe?",
    "Write about something you take for granted.",
    "List ten things that made you smile in the last week.",
    "What are you grateful for that you rarely think to mention?",
    "What has made you smile recently?",
    "What are three things you feel lucky to have?",
    "What is something you didn't appreciate before but do now?",
    "What makes you feel loved and supported?",
    "How do you express gratitude to others?",
    "What is a compliment you received that meant a lot to you?",
    "How do you celebrate small wins in your life?",
    "What are three moments of joy from the past week?",
    "Who is someone you are grateful to have in your life, and why?",
    "What is one lesson you're grateful to have learned?",
    "What is your favourite part of your daily routine?",
    "What is a small thing you're thankful for today?",
    "What is something beautiful you noticed recently?",
    "What is something good that happened today?",
    "What is a kind gesture you've done recently?",
    "What is a kind gesture you've received recently?",
    "What is your favourite way to connect with nature?",
    "An autumn memory that makes you smile.",
    "What was the last thing that made you laugh?",
    "Reflect on your happiest moment from this past week.",
    "Write about something you are grateful for from this month.",
    "Make a list of things you are grateful for.",
  ],
  growth: [
    "What has been your greatest teacher this year?",
    "Write about a time you surprised yourself.",
    "What is one habit you want to build and what's stopping you?",
    "Describe a failure that led to something better.",
    "What does courage look like in your daily life?",
    "What would you do if you weren't afraid of getting it wrong?",
    "Name one thing you've been meaning to say to someone.",
    "What is a realistic dream you have, and what is a far-fetched dream?",
    "What can you do today to be a smidgen better than yesterday?",
    "What do you wish you started doing sooner?",
    "What motivates you to keep going during difficult times?",
    "What does 'progress over perfection' mean to you?",
    "How do you measure success in your personal life?",
    "What is one new thing you'd like to learn this year?",
    "What are three things you've done this year that make you proud?",
    "What is something you want to stop procrastinating on?",
    "How do you overcome fear when trying something new?",
    "What is a skill you've been meaning to develop?",
    "How do you deal with setbacks or failure?",
    "What does living authentically mean to you?",
    "What new skills would you like to learn?",
    "Write a mantra for the last part of the year.",
    "What age did you enjoy being most?",
    "Reflect on what you have achieved this month.",
    "What is one habit you'd like to start this week?",
    "What is your most important goal for the next 30 days?",
    "How do you balance self-discipline with self-care?",
    "Write a letter to your future self. What advice do you have?",
    "What are your plans for this month?",
    "What would you regret not trying?",
    "What seeds are you planting right now?",
  ],
}

/**
 * Generate a month of prompts for a given theme.
 * Uses a seed based on month/year so the same month always gives the same schedule.
 */
export function generateMonthlySchedule(
  themeId: string,
  month: number, // 0-indexed
  year: number
): { day: number; prompt: string }[] {
  const prompts = themedPrompts[themeId] || themedPrompts.reflection
  const daysInMonth = new Date(year, month + 1, 0).getDate()

  // Seed-based shuffle so the same month/theme always gives the same result
  const seed = year * 100 + month + themeId.length * 7
  const shuffled = [...prompts]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.abs((seed * (i + 1) * 2654435761) % (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }

  const schedule = []
  for (let day = 1; day <= daysInMonth; day++) {
    schedule.push({
      day,
      prompt: shuffled[(day - 1) % shuffled.length],
    })
  }

  return schedule
}
